# Generated by Django 3.1.7 on 2021-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('grade', models.FloatField(max_length=10)),
                ('genre', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
